### Objective
Understand the dataset before performing any preprocessing or analysis.

In [56]:
import pandas as pd 
import numpy as np 
import matplotlib as plt 
import seaborn as sb

In [57]:
df = pd.read_csv("../data/raw/INDIA_AQI_COMPLETE_20251126.csv")

In [58]:
df.head()

,City,State,Latitude,Longitude,Datetime,Year,Month,Day,Hour,Day_of_Week,...,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,AQI_Category,PM25_Category_India,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
0,Agartala,Tripura,23.8315,91.2868,2022-08-05 00:00:00,2022,8,5,0,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
1,Agartala,Tripura,23.8315,91.2868,2022-08-05 01:00:00,2022,8,5,1,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
2,Agartala,Tripura,23.8315,91.2868,2022-08-05 02:00:00,2022,8,5,2,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
3,Agartala,Tripura,23.8315,91.2868,2022-08-05 03:00:00,2022,8,5,3,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0
4,Agartala,Tripura,23.8315,91.2868,2022-08-05 04:00:00,2022,8,5,4,4,...,2,NaN,NaN,NaN,NaN,Good,0,NaN,0,0

In [59]:
df.tail()

,City,State,Latitude,Longitude,Datetime,Year,Month,Day,Hour,Day_of_Week,...,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,AQI_Category,PM25_Category_India,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
842155,Visakhapatnam,Andhra Pradesh,17.6868,83.2185,2025-11-26 19:00:00,2025,11,26,19,2,...,9,118.0,118.0,81.0,Unhealthy,Moderate,0,NaN,0,1
842156,Visakhapatnam,Andhra Pradesh,17.6868,83.2185,2025-11-26 20:00:00,2025,11,26,20,2,...,9,117.0,117.0,80.0,Unhealthy,Moderate,0,NaN,0,1
842157,Visakhapatnam,Andhra Pradesh,17.6868,83.2185,2025-11-26 21:00:00,2025,11,26,21,2,...,10,116.0,116.0,80.0,Unhealthy,Moderate,0,NaN,0,1
842158,Visakhapatnam,Andhra Pradesh,17.6868,83.2185,2025-11-26 22:00:00,2025,11,26,22,2,...,10,115.0,115.0,79.0,Unhealthy,Moderate,0,NaN,0,1
842159,Visakhapatnam,Andhra Pradesh,17.6868,83.2185,2025-11-26 23:00:00,2025,11,26,23,2,...,11,114.0,114.0,79.0,Unhealthy,Moderate,0,NaN,0,1

In [60]:
print("the number of rows are :- " , df.shape[0])
print("the number of columns are :- " , df.shape[1])

the number of rows are :-  842160
the number of columns are :-  71

In [61]:
df.columns

Index(['City', 'State', 'Latitude', 'Longitude', 'Datetime', 'Year', 'Month',
       'Day', 'Hour', 'Day_of_Week', 'Day_Name', 'Week_of_Year', 'Is_Weekend',
       'Quarter', 'Season', 'Time_of_Day', 'Temp_2m_C', 'Temp_80m_C',
       'Temp_120m_C', 'Temp_180m_C', 'Humidity_Percent', 'Dew_Point_C',
       'Humidity_Category', 'Wind_Speed_10m_kmh', 'Wind_Speed_80m_kmh',
       'Wind_Speed_120m_kmh', 'Wind_Dir_10m', 'Wind_Gusts_kmh',
       'Wind_Category', 'Wind_Stagnation', 'Precipitation_mm', 'Rain_mm',
       'Is_Raining', 'Heavy_Rain', 'Pressure_MSL_hPa', 'Surface_Pressure_hPa',
       'Solar_Radiation_Wm2', 'Direct_Radiation_Wm2', 'Diffuse_Radiation_Wm2',
       'UV_Index', 'Cloud_Cover_Percent', 'Cloud_Low_Percent',
       'Cloud_Mid_Percent', 'Cloud_High_Percent', 'Is_Daytime',
       'Sunshine_Seconds', 'PM2_5_ugm3', 'PM10_ugm3', 'PM_Ratio', 'CO_ugm3',
       'NO2_ugm3', 'SO2_ugm3', 'O3_ugm3', 'Dust_ugm3', 'NH3_ugm3', 'AOD',
       'US_AQI', 'US_AQI_PM25', 'US_AQI_PM10', 'US_AQI_NO2', 'US_AQI_O3',
       'US_AQI_CO', 'EU_AQI', 'EU_AQI_PM25', 'EU_AQI_PM10', 'AQI_Category',
       'PM25_Category_India', 'Temp_Inversion', 'Inversion_Strength_C',
       'Festival_Period', 'Crop_Burning_Season'],
      dtype='object')

In [62]:
list(df.columns)

['City',
 'State',
 'Latitude',
 'Longitude',
 'Datetime',
 'Year',
 'Month',
 'Day',
 'Hour',
 'Day_of_Week',
 'Day_Name',
 'Week_of_Year',
 'Is_Weekend',
 'Quarter',
 'Season',
 'Time_of_Day',
 'Temp_2m_C',
 'Temp_80m_C',
 'Temp_120m_C',
 'Temp_180m_C',
 'Humidity_Percent',
 'Dew_Point_C',
 'Humidity_Category',
 'Wind_Speed_10m_kmh',
 'Wind_Speed_80m_kmh',
 'Wind_Speed_120m_kmh',
 'Wind_Dir_10m',
 'Wind_Gusts_kmh',
 'Wind_Category',
 'Wind_Stagnation',
 'Precipitation_mm',
 'Rain_mm',
 'Is_Raining',
 'Heavy_Rain',
 'Pressure_MSL_hPa',
 'Surface_Pressure_hPa',
 'Solar_Radiation_Wm2',
 'Direct_Radiation_Wm2',
 'Diffuse_Radiation_Wm2',
 'UV_Index',
 'Cloud_Cover_Percent',
 'Cloud_Low_Percent',
 'Cloud_Mid_Percent',
 'Cloud_High_Percent',
 'Is_Daytime',
 'Sunshine_Seconds',
 'PM2_5_ugm3',
 'PM10_ugm3',
 'PM_Ratio',
 'CO_ugm3',
 'NO2_ugm3',
 'SO2_ugm3',
 'O3_ugm3',
 'Dust_ugm3',
 'NH3_ugm3',
 'AOD',
 'US_AQI',
 'US_AQI_PM25',
 'US_AQI_PM10',
 'US_AQI_NO2',
 'US_AQI_O3',
 'US_AQI_CO',
 'EU_AQI',
 'EU_AQI_PM25',
 'EU_AQI_PM10',
 'AQI_Category',
 'PM25_Category_India',
 'Temp_Inversion',
 'Inversion_Strength_C',
 'Festival_Period',
 'Crop_Burning_Season']

In [63]:
pollutant_columns = [
    "PM2_5_ugm3",
    "PM10_ugm3",
    "CO_ugm3",
    "NO2_ugm3",
    "SO2_ugm3",
    "O3_ugm3",
    "Dust_ugm3",
    "NH3_ugm3",
    "AOD",
    "PM_Ratio"
]

In [64]:
aqi_columns = [
    "US_AQI",
    "US_AQI_PM25",
    "US_AQI_PM10",
    "US_AQI_NO2",
    "US_AQI_O3",
    "US_AQI_CO",
    "EU_AQI",
    "EU_AQI_PM25",
    "EU_AQI_PM10",
    "AQI_Category",
    "PM25_Category_India"
]

In [65]:
weather_columns = [
    "Temp_2m_C",
    "Temp_80m_C",
    "Temp_120m_C",
    "Temp_180m_C",
    "Humidity_Percent",
    "Dew_Point_C",
    "Humidity_Category",
    "Wind_Speed_10m_kmh",
    "Wind_Speed_80m_kmh",
    "Wind_Speed_120m_kmh",
    "Wind_Dir_10m",
    "Wind_Gusts_kmh",
    "Wind_Category",
    "Wind_Stagnation",
    "Precipitation_mm",
    "Rain_mm",
    "Is_Raining",
    "Heavy_Rain",
    "Pressure_MSL_hPa",
    "Surface_Pressure_hPa",
    "Solar_Radiation_Wm2",
    "Direct_Radiation_Wm2",
    "Diffuse_Radiation_Wm2",
    "UV_Index",
    "Cloud_Cover_Percent",
    "Cloud_Low_Percent",
    "Cloud_Mid_Percent",
    "Cloud_High_Percent",
    "Is_Daytime",
    "Sunshine_Seconds",
    "Temp_Inversion",
    "Inversion_Strength_C"
]

In [66]:
location_columns = [
    "City",
    "State",
    "Latitude",
    "Longitude"
]

In [67]:
time_columns = [
    "Datetime",
    "Year",
    "Month",
    "Day",
    "Hour",
    "Day_of_Week",
    "Day_Name",
    "Week_of_Year",
    "Quarter",
    "Season",
    "Time_of_Day",
    "Is_Weekend"
]

In [68]:
event_columns = [
    "Festival_Period",
    "Crop_Burning_Season"
]

In [69]:
Target = "US_AQI"

In [70]:
df.describe()

,Latitude,Longitude,Year,Month,Day,Hour,Day_of_Week,Week_of_Year,Is_Weekend,Quarter,...,US_AQI_NO2,US_AQI_O3,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
count,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,842160.000000,...,842158.000000,842087.000000,842160.000000,842015.000000,842015.000000,842015.000000,842160.0,0.0,842160.000000,842160.000000
mean,23.129041,82.769207,2023.724793,6.801653,15.736364,11.500000,3.000000,27.767769,0.285950,2.601653,...,7.961582,45.180426,4.355863,62.815243,58.034527,48.424171,0.0,NaN,0.105785,0.198347
std,5.543478,6.937205,0.995593,3.411504,8.767003,6.922191,2.000827,14.848660,0.451866,1.112661,...,10.379884,35.429652,3.892871,39.511570,31.666455,38.903157,0.0,NaN,0.307563,0.398755
min,8.524100,72.571400,2022.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,0.000000,0.000000,1.000000,5.000000,1.000000,1.000000,0.0,NaN,0.000000,0.000000
25%,20.296100,77.173400,2023.000000,4.000000,8.000000,5.750000,1.000000,15.000000,0.000000,2.000000,...,2.000000,24.000000,2.000000,36.000000,31.000000,23.000000,0.0,NaN,0.000000,0.000000
50%,23.831500,80.946200,2024.000000,7.000000,16.000000,11.500000,3.000000,29.000000,0.000000,3.000000,...,4.000000,35.000000,3.000000,62.000000,61.000000,40.000000,0.0,NaN,0.000000,0.000000
75%,26.912400,88.606500,2025.000000,10.000000,23.000000,17.250000,5.000000,41.000000,1.000000,4.000000,...,10.000000,49.000000,5.000000,77.000000,75.000000,67.000000,0.0,NaN,0.000000,0.000000
max,31.104800,94.108600,2025.000000,12.000000,31.000000,23.000000,6.000000,52.000000,1.000000,4.000000,...,115.000000,369.000000,126.000000,1179.000000,301.000000,1179.000000,0.0,NaN,1.000000,1.000000

In [71]:
df.isnull()

,City,State,Latitude,Longitude,Datetime,Year,Month,Day,Hour,Day_of_Week,...,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,AQI_Category,PM25_Category_India,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
842155,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
842156,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
842157,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
842158,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
842159,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [72]:
print(df.isnull().sum().to_string())

City                          0
State                         0
Latitude                      0
Longitude                     0
Datetime                      0
Year                          0
Month                         0
Day                           0
Hour                          0
Day_of_Week                   0
Day_Name                      0
Week_of_Year                  0
Is_Weekend                    0
Quarter                       0
Season                        0
Time_of_Day                   0
Temp_2m_C                     0
Temp_80m_C               842160
Temp_120m_C              842160
Temp_180m_C              842160
Humidity_Percent              0
Dew_Point_C                   0
Humidity_Category             0
Wind_Speed_10m_kmh            0
Wind_Speed_80m_kmh       842160
Wind_Speed_120m_kmh      842160
Wind_Dir_10m                  0
Wind_Gusts_kmh                0
Wind_Category                 0
Wind_Stagnation               0
Precipitation_mm              0
Rain_mm                       0
Is_Raining                    0
Heavy_Rain                    0
Pressure_MSL_hPa              0
Surface_Pressure_hPa          0
Solar_Radiation_Wm2           0
Direct_Radiation_Wm2          0
Diffuse_Radiation_Wm2         0
UV_Index                 842160
Cloud_Cover_Percent           0
Cloud_Low_Percent             0
Cloud_Mid_Percent             0
Cloud_High_Percent            0
Is_Daytime                    0
Sunshine_Seconds              0
PM2_5_ugm3                    0
PM10_ugm3                     0
PM_Ratio                      0
CO_ugm3                       0
NO2_ugm3                      0
SO2_ugm3                      0
O3_ugm3                       0
Dust_ugm3                     0
NH3_ugm3                 842160
AOD                           0
US_AQI                      145
US_AQI_PM25                 145
US_AQI_PM10                 145
US_AQI_NO2                    2
US_AQI_O3                    73
US_AQI_CO                     0
EU_AQI                      145
EU_AQI_PM25                 145
EU_AQI_PM10                 145
AQI_Category               2516
PM25_Category_India           2
Temp_Inversion                0
Inversion_Strength_C     842160
Festival_Period               0
Crop_Burning_Season           0

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842160 entries, 0 to 842159
Data columns (total 71 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   City                   842160 non-null  object
 1   State                  842160 non-null  object
 2   Latitude               842160 non-null  float64
 3   Longitude              842160 non-null  float64
 4   Datetime               842160 non-null  object
 5   Year                   842160 non-null  int64
 6   Month                  842160 non-null  int64
 7   Day                    842160 non-null  int64
 8   Hour                   842160 non-null  int64
 9   Day_of_Week            842160 non-null  int64
 10  Day_Name               842160 non-null  object
 11  Week_of_Year           842160 non-null  int64
 12  Is_Weekend             842160 non-null  int64
 13  Quarter                842160 non-null  int64
 14  Season                 842160 non-null  object
 15  Time_of_Day            842160 non-null  object
 16  Temp_2m_C              842160 non-null  float64
 17  Temp_80m_C             0 non-null       float64
 18  Temp_120m_C            0 non-null       float64
 19  Temp_180m_C            0 non-null       float64
 20  Humidity_Percent       842160 non-null  int64
 21  Dew_Point_C            842160 non-null  float64
 22  Humidity_Category      842160 non-null  object
 23  Wind_Speed_10m_kmh     842160 non-null  float64
 24  Wind_Speed_80m_kmh     0 non-null       float64
 25  Wind_Speed_120m_kmh    0 non-null       float64
 26  Wind_Dir_10m           842160 non-null  int64
 27  Wind_Gusts_kmh         842160 non-null  float64
 28  Wind_Category          842160 non-null  object
 29  Wind_Stagnation        842160 non-null  int64
 30  Precipitation_mm       842160 non-null  float64
 31  Rain_mm                842160 non-null  float64
 32  Is_Raining             842160 non-null  int64
 33  Heavy_Rain             842160 non-null  int64
 34  Pressure_MSL_hPa       842160 non-null  float64
 35  Surface_Pressure_hPa   842160 non-null  float64
 36  Solar_Radiation_Wm2    842160 non-null  float64
 37  Direct_Radiation_Wm2   842160 non-null  float64
 38  Diffuse_Radiation_Wm2  842160 non-null  float64
 39  UV_Index               0 non-null       float64
 40  Cloud_Cover_Percent    842160 non-null  int64
 41  Cloud_Low_Percent      842160 non-null  int64
 42  Cloud_Mid_Percent      842160 non-null  int64
 43  Cloud_High_Percent     842160 non-null  int64
 44  Is_Daytime             842160 non-null  int64
 45  Sunshine_Seconds       842160 non-null  float64
 46  PM2_5_ugm3             842160 non-null  float64
 47  PM10_ugm3              842160 non-null  float64
 48  PM_Ratio               842160 non-null  float64
 49  CO_ugm3                842160 non-null  float64
 50  NO2_ugm3               842160 non-null  float64
 51  SO2_ugm3               842160 non-null  float64
 52  O3_ugm3                842160 non-null  float64
 53  Dust_ugm3              842160 non-null  float64
 54  NH3_ugm3               0 non-null       float64
 55  AOD                    842160 non-null  float64
 56  US_AQI                 842015 non-null  float64
 57  US_AQI_PM25            842015 non-null  float64
 58  US_AQI_PM10            842015 non-null  float64
 59  US_AQI_NO2             842158 non-null  float64
 60  US_AQI_O3              842087 non-null  float64
 61  US_AQI_CO              842160 non-null  int64
 62  EU_AQI                 842015 non-null  float64
 63  EU_AQI_PM25            842015 non-null  float64
 64  EU_AQI_PM10            842015 non-null  float64
 65  AQI_Category           839644 non-null  object
 66  PM25_Category_India    842158 non-null  object
 67  Temp_Inversion         842160 non-null  int64
 68  Inversion_Strength_C   0 non-null       float64
 69  Festival_Period        842160 non-null  int64
 70  Crop_Burning_Season    842160 non-null  int64
dtypes: float64(39), int64(22), object(10)
memory usage: 456.2+ MB

In [74]:
print(df.dtypes.unique())

[dtype('O') dtype('float64') dtype('int64')]

In [75]:
numerical_columns = df.select_dtypes(include = ['float64' , 'int64']).columns.tolist()

In [76]:
numerical_columns

['Latitude',
 'Longitude',
 'Year',
 'Month',
 'Day',
 'Hour',
 'Day_of_Week',
 'Week_of_Year',
 'Is_Weekend',
 'Quarter',
 'Temp_2m_C',
 'Temp_80m_C',
 'Temp_120m_C',
 'Temp_180m_C',
 'Humidity_Percent',
 'Dew_Point_C',
 'Wind_Speed_10m_kmh',
 'Wind_Speed_80m_kmh',
 'Wind_Speed_120m_kmh',
 'Wind_Dir_10m',
 'Wind_Gusts_kmh',
 'Wind_Stagnation',
 'Precipitation_mm',
 'Rain_mm',
 'Is_Raining',
 'Heavy_Rain',
 'Pressure_MSL_hPa',
 'Surface_Pressure_hPa',
 'Solar_Radiation_Wm2',
 'Direct_Radiation_Wm2',
 'Diffuse_Radiation_Wm2',
 'UV_Index',
 'Cloud_Cover_Percent',
 'Cloud_Low_Percent',
 'Cloud_Mid_Percent',
 'Cloud_High_Percent',
 'Is_Daytime',
 'Sunshine_Seconds',
 'PM2_5_ugm3',
 'PM10_ugm3',
 'PM_Ratio',
 'CO_ugm3',
 'NO2_ugm3',
 'SO2_ugm3',
 'O3_ugm3',
 'Dust_ugm3',
 'NH3_ugm3',
 'AOD',
 'US_AQI',
 'US_AQI_PM25',
 'US_AQI_PM10',
 'US_AQI_NO2',
 'US_AQI_O3',
 'US_AQI_CO',
 'EU_AQI',
 'EU_AQI_PM25',
 'EU_AQI_PM10',
 'Temp_Inversion',
 'Inversion_Strength_C',
 'Festival_Period',
 'Crop_Burning_Season']

In [77]:
categorical_columns = df.select_dtypes(include = ['object']).columns.tolist()

In [78]:
categorical_columns

['City',
 'State',
 'Datetime',
 'Day_Name',
 'Season',
 'Time_of_Day',
 'Humidity_Category',
 'Wind_Category',
 'AQI_Category',
 'PM25_Category_India']

In [79]:
numerical_columns_length = len(numerical_columns)
print(numerical_columns_length)

61

In [80]:
categorical_columns_length = len(categorical_columns)
print(categorical_columns_length)

10

In [81]:
df.columns

Index(['City', 'State', 'Latitude', 'Longitude', 'Datetime', 'Year', 'Month',
       'Day', 'Hour', 'Day_of_Week', 'Day_Name', 'Week_of_Year', 'Is_Weekend',
       'Quarter', 'Season', 'Time_of_Day', 'Temp_2m_C', 'Temp_80m_C',
       'Temp_120m_C', 'Temp_180m_C', 'Humidity_Percent', 'Dew_Point_C',
       'Humidity_Category', 'Wind_Speed_10m_kmh', 'Wind_Speed_80m_kmh',
       'Wind_Speed_120m_kmh', 'Wind_Dir_10m', 'Wind_Gusts_kmh',
       'Wind_Category', 'Wind_Stagnation', 'Precipitation_mm', 'Rain_mm',
       'Is_Raining', 'Heavy_Rain', 'Pressure_MSL_hPa', 'Surface_Pressure_hPa',
       'Solar_Radiation_Wm2', 'Direct_Radiation_Wm2', 'Diffuse_Radiation_Wm2',
       'UV_Index', 'Cloud_Cover_Percent', 'Cloud_Low_Percent',
       'Cloud_Mid_Percent', 'Cloud_High_Percent', 'Is_Daytime',
       'Sunshine_Seconds', 'PM2_5_ugm3', 'PM10_ugm3', 'PM_Ratio', 'CO_ugm3',
       'NO2_ugm3', 'SO2_ugm3', 'O3_ugm3', 'Dust_ugm3', 'NH3_ugm3', 'AOD',
       'US_AQI', 'US_AQI_PM25', 'US_AQI_PM10', 'US_AQI_NO2', 'US_AQI_O3',
       'US_AQI_CO', 'EU_AQI', 'EU_AQI_PM25', 'EU_AQI_PM10', 'AQI_Category',
       'PM25_Category_India', 'Temp_Inversion', 'Inversion_Strength_C',
       'Festival_Period', 'Crop_Burning_Season'],
      dtype='object')

In [82]:
for i in (categorical_columns):
    print(df[i].unique())
    print("-------------------------------------------------------------------------------------")

['Agartala' 'Ahmedabad' 'Aizawl' 'Bengaluru' 'Bhopal' 'Bhubaneswar'
 'Chandigarh' 'Chennai' 'Dehradun' 'Delhi' 'Gangtok' 'Gurugram' 'Guwahati'
 'Hyderabad' 'Imphal' 'Itanagar' 'Jaipur' 'Kohima' 'Kolkata' 'Lucknow'
 'Mumbai' 'Panaji' 'Patna' 'Raipur' 'Ranchi' 'Shillong' 'Shimla'
 'Thiruvananthapuram' 'Visakhapatnam']
-------------------------------------------------------------------------------------
['Tripura' 'Gujarat' 'Mizoram' 'Karnataka' 'Madhya Pradesh' 'Odisha'
 'Punjab' 'Tamil Nadu' 'Uttarakhand' 'Delhi' 'Sikkim' 'Haryana' 'Assam'
 'Telangana' 'Manipur' 'Arunachal Pradesh' 'Rajasthan' 'Nagaland'
 'West Bengal' 'Uttar Pradesh' 'Maharashtra' 'Goa' 'Bihar' 'Chhattisgarh'
 'Jharkhand' 'Meghalaya' 'Himachal Pradesh' 'Kerala' 'Andhra Pradesh']
-------------------------------------------------------------------------------------
['2022-08-05 00:00:00' '2022-08-05 01:00:00' '2022-08-05 02:00:00' ...
 '2025-11-26 21:00:00' '2025-11-26 22:00:00' '2025-11-26 23:00:00']
-------------------------------------------------------------------------------------
['Friday' 'Saturday' 'Sunday' 'Monday' 'Tuesday' 'Wednesday' 'Thursday']
-------------------------------------------------------------------------------------
['Monsoon' 'Post_Monsoon' 'Winter' 'Summer']
-------------------------------------------------------------------------------------
['Night' 'Early_Morning' 'Morning' 'Afternoon' 'Evening' 'Night_Late']
-------------------------------------------------------------------------------------
['Very_Humid' 'Humid' 'Comfortable' 'Dry' 'Very_Dry']
-------------------------------------------------------------------------------------
['Moderate' 'Light' 'Calm' 'Fresh' 'Strong']
-------------------------------------------------------------------------------------
[nan 'Moderate' 'Good' 'Unhealthy_Sensitive' 'Unhealthy' 'Very_Unhealthy'
 'Hazardous']
-------------------------------------------------------------------------------------
['Good' 'Satisfactory' 'Moderate' 'Poor' 'Very_Poor' 'Severe' nan]
-------------------------------------------------------------------------------------

In this notebook, we explored the overall structure of the dataset without modifying it. We identified the number of observations, feature types, target variable, summary statistics, and initial characteristics. The next notebook will focus on assessing data quality, including missing values, duplicates, invalid entries, and inconsistencies.

# Objective

The purpose of this notebook is to understand the dataset before performing any preprocessing or analysis.

At this stage, the objective is not to modify the data but to study its overall structure, identify the available features, understand the target variable, and gain an initial understanding of the information available for building the AirGuardian AI prediction system.

---

## Import Required Libraries

The first step is to import the necessary Python libraries that will be used throughout this notebook. These libraries provide functionalities for data loading, numerical computations, visualization, and basic data exploration.

---

## Load the Dataset

The dataset is loaded into a Pandas DataFrame to enable efficient exploration and analysis. Once loaded, all subsequent operations in this notebook will be performed on this DataFrame.

---

## Display the First Five Records

Displaying the first few rows helps verify that the dataset has been loaded correctly. It also provides an initial understanding of the available features and the overall structure of the data.

---

## Display the Last Five Records

Inspecting the last few rows ensures that the dataset has been imported completely and helps identify any obvious inconsistencies or irregularities near the end of the dataset.

---

## Determine Dataset Dimensions

The dimensions of the dataset are examined to understand the total number of observations and features available for analysis. This provides a quick overview of the dataset's size.

---

## Explore Available Features

The complete list of column names is displayed to understand the information captured in the dataset. Each column represents a potential feature that may contribute to predicting the Air Quality Index.

---

## Identify Pollution-Related Features

The pollutant concentration columns are identified separately since these variables are expected to have the strongest influence on air quality prediction.

---

## Identify AQI-Related Features

The dataset contains multiple AQI-related attributes, including pollutant-specific AQI values and the overall Air Quality Index. These columns are identified for better understanding of the target and supporting variables.

---

## Identify Weather Features

Weather conditions significantly influence pollutant dispersion and air quality. These variables are grouped separately for organized analysis in later stages.

---

## Identify Geographical Features

Location-based attributes such as city, state, latitude, and longitude are identified to support geographical analysis of pollution patterns.

---

## Identify Time-Based Features

Time-related variables are important because air pollution changes across different days, months, seasons, and years. These features will be useful for future time-series analysis.

---

## Identify Event-Based Features

Certain environmental or human activities, such as festivals and crop-burning events, may affect pollution levels. These variables are identified separately as they may become useful during feature engineering.

---

## Define the Target Variable

The primary objective of this project is to predict the overall Air Quality Index (US_AQI). This variable will be treated as the target during model development.

---

## Generate Descriptive Statistics

Descriptive statistics provide a summary of the numerical features, including measures of central tendency and variability. This helps develop an initial understanding of the dataset before performing detailed analysis.

---

## Check for Missing Values

Before applying any preprocessing techniques, it is important to determine whether the dataset contains missing information. At this stage, missing values are only identified and not modified.

---

## Count Missing Values

The number of missing values present in each feature is calculated to identify columns that may require preprocessing during the data cleaning phase.

---

## Dataset Information

The overall structure of the dataset is examined using dataset information, including the number of observations, non-null values, data types, and memory usage. This provides a comprehensive overview of the dataset.

---

## Inspect Data Types

The data type of each feature is examined because different preprocessing and machine learning techniques are applied depending on whether a feature is numerical, categorical, or datetime.

---

## Identify Numerical Features

All numerical features are extracted separately. These variables will be analyzed extensively during the Exploratory Data Analysis phase.

---

## Identify Categorical Features

Categorical variables are identified separately since they require different preprocessing techniques compared to numerical variables.

---

## Count Numerical Features

The total number of numerical features is calculated to better understand the overall composition of the dataset.

---

## Count Categorical Features

The total number of categorical variables is determined before performing detailed categorical data analysis.

---

## Explore Unique Categories

The unique values present in each categorical feature are examined to understand the diversity of categories and to identify any inconsistent or unexpected values.

---

# Conclusion

In this notebook, the dataset was explored without making any modifications.

The overall structure, dimensions, available features, target variable, summary statistics, missing values, data types, and feature categories were examined to gain a clear understanding of the dataset.

This initial exploration establishes a strong foundation for the subsequent stages of the project. The next notebook will focus on **Univariate Exploratory Data Analysis (EDA)**, where each feature will be analyzed individually to understand its distribution, variability, skewness, and potential outliers before any preprocessing begins.